env:
  ANKA_MOJAVE_TEMPLATE: "10.14.4_6C_14G_40G"
  ANKA_TEMPLATE_TAG: "clean::cicd::git-ssh::nas::brew"
  CHECKSUMABLE: "scripts/eosio_build*"
  MAC_TAG: "eosio_2-5"
  WORKDIR: "/private/var/tmp/ankafs.0"

steps:

  # - trigger: "mac-anka-fleet"
  #   label: ":anka: Ensure Mojave Anka Template Tag Exists"
  #   branches: "*"
  #   async: false
  #   build:
  #     branch: "master"
  #     env:
  #       REPO: "${BUILDKITE_REPO}"
  #       REPO_BRANCH: "${BUILDKITE_BRANCH}"
  #       CHECKSUMABLE: "${CHECKSUMABLE}"
  #       TEMPLATE: "${ANKA_MOJAVE_TEMPLATE}"
  #       TEMPLATE_TAG: "${ANKA_TEMPLATE_TAG}"
  #       TAG_COMMANDS: "CLONED_REPO_DIR/scripts/eosio_build.sh -y -P -f -m" # CLONED_REPO_DIR IS REQUIRED and is where the repo is always cloned into
  #       PROJECT_TAG: "${MAC_TAG}"

  # - wait

  # - label: ":darwin: [Darwin] Mojave Build"
  #   command:
  #     - "./scripts/eosio_build.sh -y -P"
  #     - "tar -pczf /Network/NAS/MAC_FLEET/BUILDKITE/artifacts/${ANKA_MOJAVE_TEMPLATE}-${BUILDKITE_PIPELINE_SLUG}-${BUILDKITE_BUILD_ID}.tar.gz build"
  #   plugins:
  #     chef/anka#v0.4.4:
  #       vm-name: $ANKA_MOJAVE_TEMPLATE
  #       vm-registry-tag: "${ANKA_TEMPLATE_TAG}::${MAC_TAG}"
  #       always-pull: true
  #       debug: true
  #       wait-network: true
  #   agents:
  #     - "queue=mac-anka-node-fleet"
  #   timeout: 120

  # - wait

  # - label: ":darwin: [Darwin] Mojave Tests"
  #   command:
  #     # ssh needed to work around tty limitations of anka run (they're releasing a fix in the next major version)
  #     # - "ssh -i ~/.ssh/localhost anka@localhost \"cd $WORKDIR && PATH=$PATH ./scripts/parallel-test.sh /Network/NAS/MAC_FLEET/BUILDKITE/artifacts/10.14.4_6C_14G_40G-eosio-e65cbc54-7804-4c89-97a2-842a9c03c42a.tar.gz\"; echo $?"
  #     - "cd $WORKDIR && PATH=$PATH ./scripts/parallel-test.sh /Network/NAS/MAC_FLEET/BUILDKITE/artifacts/10.14.4_6C_14G_40G-eosio-e65cbc54-7804-4c89-97a2-842a9c03c42a.tar.gz"

  #   artifact_paths:
  #     - "build/genesis.json"
  #     - "build/config.ini"
  #     - "build/test-results.xml"
  #   agents:
  #     - "queue=mac-anka-node-fleet"
  #   plugins:
  #     chef/anka#v0.4.4:
  #       anka-debug: true
  #       vm-name: $ANKA_MOJAVE_TEMPLATE
  #       vm-registry-tag: "${ANKA_TEMPLATE_TAG}::${MAC_TAG}"
  #       always-pull: true
  #       debug: true
  #       wait-network: true
  #   timeout: 120

  - label: ":darwin: [Darwin] Mojave Tests"
    command:
      - "mkdir -p /private/var/tmp/ankafs.0 && cd /private/var/tmp/ankafs.0 && tar -xzf /Network/NAS/MAC_FLEET/BUILDKITE/artifacts/10.14.4_6C_14G_40G-eosio-e65cbc54-7804-4c89-97a2-842a9c03c42a.tar.gz"
      - "cd /private/var/tmp/ankafs.0/build && ctest -L nonparallelizable_tests --progress --output-on-failure -T Test"
    artifact_paths:
      - "build/mongod.log"
      - "build/genesis.json"
      - "build/config.ini"
      - "build/test-results.xml"
    agents:
      - "queue=mac-anka-node-fleet"
    plugins:
      chef/anka#v0.4.4:
        no-volume: true
        vm-name: $ANKA_MOJAVE_TEMPLATE
        vm-registry-tag: "${ANKA_TEMPLATE_TAG}::${MAC_TAG}"
        always-pull: true
        debug: true
        wait-network: true
    timeout: 120
