env:
  ANKA_MOJAVE_TEMPLATE: "10.14.4_6C_14G_40G"
  ANKA_TEMPLATE_TAG: "clean::cicd::git-ssh::nas::brew"
  CHECKSUMABLE: "scripts/eosio_build*"
  MAC_TAG: "eosio_2-4"
  WORKDIR: "/private/var/tmp/ankafs.0"

steps:

  # - trigger: "mac-anka-fleet"
  #   label: ":anka: Ensure Mojave Anka Template Tag Exists"
  #   branches: "*"
  #   async: false
  #   build:
  #     branch: "master"
  #     env:
  #       REPO: "${BUILDKITE_REPO}"
  #       REPO_BRANCH: "${BUILDKITE_BRANCH}"
  #       CHECKSUMABLE: "${CHECKSUMABLE}"
  #       TEMPLATE: "${ANKA_MOJAVE_TEMPLATE}"
  #       TEMPLATE_TAG: "${ANKA_TEMPLATE_TAG}"
  #       TAG_COMMANDS: "CLONED_REPO_DIR/scripts/eosio_build.sh -y -P -f -m" # CLONED_REPO_DIR IS REQUIRED and is where the repo is always cloned into
  #       PROJECT_TAG: "${MAC_TAG}"

  # - wait

  - label: ":darwin: [Darwin] Mojave Build"
    command:
      - "./scripts/eosio_build.sh -y -P"
      - "tar -pczf /Network/NAS/MAC_FLEET/BUILDKITE/artifacts/${ANKA_MOJAVE_TEMPLATE}-${BUILDKITE_PIPELINE_SLUG}-${BUILDKITE_BUILD_ID}.tar.gz build"
    plugins:
      chef/anka#v0.4.4:
        host-commands:
          - "echo \"test\""
          - "echo \"test2\""
          - "buildkite-agent download artifact \"testing123\""  
        vm-name: $ANKA_MOJAVE_TEMPLATE
        vm-registry-tag: "${ANKA_TEMPLATE_TAG}::${MAC_TAG}"
        always-pull: true
        debug: true
        wait-network: true
    agents:
      - "queue=mac-anka-node-fleet"
    timeout: 120

  - wait

  - label: ":darwin: [Darwin] Mojave Tests"
    command:
      # ssh needed to work around tty limitations of anka run (they're releasing a fix in the next major version)
      - "ssh -i ~/.ssh/localhost anka@localhost \"cd $WORKDIR && PATH=$PATH ./scripts/parallel-test.sh"
    artifact_paths:
      - "build/genesis.json"
      - "build/config.ini"
      - "build/test-results.xml"
    agents:
      - "queue=nathan"
    plugins:
      chef/anka#v0.4.4:
        vm-name: $ANKA_MOJAVE_TEMPLATE
        vm-registry-tag: "${ANKA_TEMPLATE_TAG}::${MAC_TAG}"
        always-pull: true
        debug: true
        wait-network: true
    timeout: 120

  - label: ":darwin: [Darwin] Mojave Tests"
    command:
      - "ssh -i ~/.ssh/localhost anka@localhost \"cd $WORKDIR && PATH=$PATH ./scripts/serial-test.sh"
    artifact_paths:
      - "build/mongod.log"
      - "build/genesis.json"
      - "build/config.ini"
      - "build/test-results.xml"
    agents:
      - "queue=mac-anka-node-fleet"
    plugins:
      chef/anka#v0.4.3:
        vm-name: $ANKA_MOJAVE_TEMPLATE
        vm-registry-tag: "${ANKA_TEMPLATE_TAG}::${MAC_TAG}"
        always-pull: true
        debug: true
        wait-network: true
    timeout: 120
